# Generated by Django 2.0.5 on 2018-05-28 22:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('dump', django.contrib.postgres.fields.jsonb.JSONField()),
                ('modified_time', models.IntegerField()),
            ],
        ),
    ]
